# Generated by Django 3.0.3 on 2020-02-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_title', models.CharField(max_length=40)),
                ('coin_desc', models.TextField()),
            ],
        ),
    ]
