# Generated by Django 3.0.3 on 2020-02-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coin_cat',
            field=models.CharField(choices=[('sh', 'shitcoin'), ('pu', 'pumpndump'), ('dg', 'digitalgold'), ('co', 'coordinatordown')], default='sh', max_length=15),
        ),
    ]
